### ISSUE TITLE
Empty repo

### ISSUE THREAD

**Issue by Zehir** [centreon/centreon-dummy#1]
Hello,

I seek for the dummy module center.
I thought it would be here, but this repo is empty

Thank

**Comment by guillaumechardin** [comment]
trying to devellop a nrdsmanager module but need this exemple to get it done. Can you populate it with content ?

**Comment by kozfelipe** [comment]
I followed all the documentation steps to create a module but I got stuck in my topology page:

![image](https://user-images.githubusercontent.com/25208457/49168693-3267cf80-f31f-11e8-9c65-b3b17cf1bdf8.png)

**Comment by ganoze** [comment]
Finally, repository got filled up.
